version: "2"
run:
  timeout: 5m
  tests: true
  go: "1.24.4"
linters:
  enable:
    - dupl
    - godox
    - gosec
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nolintlint
    - perfsprint
    - testifylint
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - goconst
          - gosec
          - errcheck
          - mnd
formatters:
  enable:
    - gofumpt
    - golines
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes: [github.com/esacteksab/gh-tp]
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: false
      reformat-tags: true
      chain-split-dots: true
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
